### ISSUE TITLE
Diane's Umbrella Issue

### ISSUE THREAD

**Issue by yeo88** [ShreyaV-05/Waves#13]
Week of 5/24-6/7: Cafe Information page and Cafe Review and Recommendation Forms
- [x] [#2 ](https://github.com/ShreyaV-05/Waves/issues/2 )

Search Bar + Music play button:
- [ ] [#6 ](https://github.com/ShreyaV-05/Waves/issues/6)

Week of 6/7-6/11: Finalizing Searchbar + creating databases for the review and recommendation form pages
- [x] [#2 ](https://github.com/ShreyaV-05/Waves/issues/2 )
- [ ] [#6 ](https://github.com/ShreyaV-05/Waves/issues/6)

**Comment by ShreyaV-05** [comment]
I love the sections of your review form and I adore the way your cafe page looks so aesthetically appealing! Can't wait to see how and where you plan to display the data from your review forms. Would you be making a separate page for them or displaying the reviews on the same page as the cafes?

**Comment by ShreyaV-05** [comment]
Great job making your database backend and formulating the review maps! It was very nice working with you and it really helped me personally learn more about databases since I was looking at it in a different perspective.

**Comment by andrea-abed** [comment]
Great effort into working on the database for both the reviews and recommend pages, it really helped working with you and shreya to catch each others mistakes and understand each others thinking.
