### ISSUE TITLE
Shreya's Umbrella Issue

### ISSUE THREAD

**Issue by ShreyaV-05** [ShreyaV-05/Waves#9]
Week of 5/24-6/1: Databases and Connecting pages for books:

- [x] https://github.com/ShreyaV-05/Waves/issues/7#issue-899865693 

Week of 6/1-6/9: Navbar and books html template:

- [x] https://github.com/ShreyaV-05/Waves/issues/10#issue-908540463

Week of 6/7-6/11: Adding reviews and recommendations on book and bookstore template and making pages pretty

- [x] https://github.com/ShreyaV-05/Waves/issues/11#issue-908542098

**Comment by yeo88** [comment]
You seem like you're doing a lot! Thanks for adding those links too they were really helpful.

**Comment by RyanLuo1** [comment]
Shreya, way to take the lead for databases! I loved collaborating and splitting up the database section and rest api section so we had full coverage of the rubric throughout our project! You seem extremely organized with your databases.

**Comment by yeo88** [comment]
Hi Shreya, I really loved how you formatted your pages for the book and bookstore recommendations. It was incredibly user-friendly and organized! I also liked how your categories was color-coded and uniform. Very informational and convenient!

**Comment by andrea-abed** [comment]
same, i agree with diane! it's very organized and well put together!
